name: xam_shoes_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+14

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.6
  get: ^4.6.5
  animate_do: ^3.0.2
  mobile_scanner: ^3.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  intl: ^0.18.1
  permission_handler: ^10.3.0
  sticky_grouped_list: ^3.1.0
  carousel_slider: ^4.2.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  web:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Black.otf
          weight: 900
        - asset: assets/fonts/SFUIDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/SFUIDisplay-Heavy.otf
          weight: 800
        - asset: assets/fonts/SFUIDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/SFUIDisplay-Medium.otf
          weight: 400
        - asset: assets/fonts/SFUIDisplay-Semibold.otf
          weight: 500
        - asset: assets/fonts/SFUIDisplay-Thin.otf
          weight: 200
        - asset: assets/fonts/SFUIDisplay-Ultralight.otf
          weight: 100
